### 1. Criar uma nova conta (Registo)
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "name": "Giancarlo",
  "email": "admin@minhaloja.com",
  "password": "senha-super-segura"
}

### 2. Fazer Login
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "admin@minhaloja.com",
  "password": "senha-super-segura"
}
### 3. Cadastrar Produto na Loja (Seguro)
POST http://localhost:8081/api/produtos
Content-Type: application/json
Authorization: Bearer COLA_AQUI_O_TEU_TOKEN_GIGANTE

{
  "name": "E-book: Como Programar em Java",
  "description": "Aprende Spring Boot do zero",
  "price": 49.90
}

### 4. Listar Produtos da Minha Loja (Seguro)
GET http://localhost:8081/api/produtos
Authorization: Bearer COLA_AQUI_O_TEU_TOKEN_GIGANTE